version: '3.8'

services:
  # Mosquitto MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: whofi-mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped

  # CSI Processing Server
  csi-processor:
    build: ./docker
    container_name: whofi-processor
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - LOG_LEVEL=INFO
    volumes:
      - ./docker/config.yaml:/app/config.yaml
      - ./models:/app/models  # For future ML models
    restart: unless-stopped
    
  # Optional: InfluxDB for time-series data
  influxdb:
    image: influxdb:2.7
    container_name: whofi-influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=whofi
      - DOCKER_INFLUXDB_INIT_BUCKET=csi_data
    volumes:
      - influxdb-data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    restart: unless-stopped

  # Optional: Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: whofi-grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  influxdb-data:
  grafana-data: