apiVersion: v1
kind: Secret
metadata:
  name: whofi-github-secret
  namespace: github-actions-runners
type: Opaque
stringData:
  # GitHub App Configuration (Recommended)
  # Create a GitHub App for the whofi repository with these permissions:
  # - Actions: Read
  # - Administration: Read/Write  
  # - Metadata: Read
  # Then use the App ID and Private Key below
  
  # Option 1: GitHub App (Recommended for production)
  github_app_id: ""
  github_app_installation_id: ""
  github_app_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    YOUR_GITHUB_APP_PRIVATE_KEY_HERE
    -----END RSA PRIVATE KEY-----
  
  # Option 2: Personal Access Token (simpler setup)
  # Create a PAT with these scopes:
  # - repo (Full control of private repositories)
  # - workflow (Update GitHub Action workflows)
  github_token: ""
  
---
# Sealed Secret version (for ArgoCD deployment)
# Use: kubeseal --format=yaml < whofi-github-secret.yaml > whofi-github-sealedsecret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: whofi-github-secret
  namespace: github-actions-runners
spec:
  encryptedData:
    # These will be populated by kubeseal
    github_app_id: ""
    github_app_installation_id: ""
    github_app_private_key: ""
    github_token: ""
  template:
    metadata:
      name: whofi-github-secret
      namespace: github-actions-runners
    type: Opaque