version: '3.8'

# Production docker-compose using pre-built images from GHCR
# Usage: docker-compose -f docker-compose.prod.yml up -d

services:
  # MQTT Broker (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: csi-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/mosquitto/passwd:/mosquitto/config/passwd
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    restart: unless-stopped
    networks:
      - csi_network

  # SQLite Database (via backend service)
  # Note: SQLite is embedded in the backend service

  # NTP Server (Chrony)
  chrony:
    image: publicarray/chrony:latest
    container_name: csi-ntp
    ports:
      - "123:123/udp"
    environment:
      - NTP_SERVERS=pool.ntp.org
    volumes:
      - ./config/chrony/chrony.conf:/etc/chrony/chrony.conf:ro
    restart: unless-stopped
    networks:
      - csi_network

  # Backend API Server (Node.js) - From GHCR
  backend:
    image: ghcr.io/jedarden-org/whofi-backend:latest
    container_name: csi-backend
    ports:
      - "3000:3000"
      - "8080:8080"  # WebSocket port
    environment:
      - NODE_ENV=production
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
      - MQTT_USERNAME=csi_user
      - MQTT_PASSWORD=${MQTT_PASSWORD:-changeme}
      - NTP_SERVER=chrony
      - DB_PATH=/app/data/csi.db
      - JWT_SECRET=${JWT_SECRET:-changeme}
      - API_KEY=${API_KEY:-changeme}
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    depends_on:
      - mosquitto
      - chrony
    restart: unless-stopped
    networks:
      - csi_network

  # Frontend Web Server (Nginx + React) - From GHCR
  frontend:
    image: ghcr.io/jedarden-org/whofi-frontend:latest
    container_name: csi-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - csi_network

volumes:
  mosquitto_data:
  mosquitto_logs:

networks:
  csi_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16